// cormorant_addr_map.svh
// AUTO-GENERATED by gen_addr_map.tcl — do not edit manually.
// Regenerate: source gen_addr_map.tcl  (Vivado Tcl console)
// Source HWH: design_cormorant.hwh

localparam logic [39:0] ConvKernel_0_BASE = 40'hA002_0000;
localparam logic [39:0] MatmulKernel_0_BASE = 40'hA001_0000;
localparam logic [39:0] PoolingKernel_0_BASE = 40'hA003_0000;
localparam logic [39:0] VectorOPKernel_0_BASE = 40'hA000_0000;
