# gen_addr_map.tcl
# Reads design_cormorant.hwh and generates cormorant_addr_map.svh with one
# localparam per kernel AXI-Lite control base address.
#
# Usage (Vivado Tcl console or batch mode):
#   source .../sim_1/new/gen_addr_map.tcl
#
# To run automatically before simulation:
#   Project Settings → Simulation → Elaboration → Pre-elaboration TCL commands
#   → add:  source [file join [file dirname [info script]] gen_addr_map.tcl]

set script_dir [file normalize [file dirname [info script]]]

# Locate design_cormorant.hwh.  Check the standard generated path first, then
# fall back to a recursive search from the Vivado project root.
set proj_root [file normalize [file join $script_dir ../../..]]
set hwh_path  ""

foreach candidate [list \
    [file join $proj_root cormorant_hw.gen sources_1 bd design_cormorant hw_handoff design_cormorant.hwh]] {
    if {[file exists $candidate]} {
        set hwh_path $candidate
        break
    }
}

if {$hwh_path eq ""} {
    set hits [glob -nocomplain -directory $proj_root -type f design_cormorant.hwh]
    if {[llength $hits]} { set hwh_path [lindex $hits 0] }
}

if {$hwh_path eq ""} {
    error "gen_addr_map.tcl: cannot find design_cormorant.hwh under $proj_root"
}

puts "gen_addr_map.tcl: reading [file tail $hwh_path]"

set fp  [open $hwh_path r]
set xml [read $fp]
close $fp

# Extract MEMRANGE lines that describe AXI-Lite control register regions.
# These have ADDRESSBLOCK="Reg" and SLAVEBUSINTERFACE="s_axi_ctrl".
array set bases {}
foreach line [split $xml "\n"] {
    set line [string trim $line]
    if {![string match {*<MEMRANGE*} $line]}              continue
    if {![string match {*ADDRESSBLOCK="Reg"*} $line]}     continue
    if {![string match {*SLAVEBUSINTERFACE="s_axi_ctrl"*} $line]} continue

    set inst ""; set base ""
    regexp {INSTANCE="([^"]+)"}  $line -> inst
    regexp {BASEVALUE="(0x[0-9A-Fa-f]+)"} $line -> base

    if {$inst ne "" && $base ne ""} {
        set bases($inst) $base
    }
}

if {[array size bases] == 0} {
    error "gen_addr_map.tcl: no AXI-Lite control regions found in [file tail $hwh_path]"
}

# Format a hex string as a 40-bit SV literal:  0xA0000000 → 40'hA000_0000
proc to_sv40 {hex_str} {
    set hex [string toupper [string range $hex_str 2 end]]
    # Right-pad to 10 hex digits then keep the low 8 for the 32-bit address portion
    set hex10 [format "%010s" $hex]
    set hex10 [string map {{ } 0} $hex10]
    set hi2   [string range $hex10 0 1]
    set lo8hi [string range $hex10 2 5]
    set lo8lo [string range $hex10 6 9]
    # Omit leading "00" if the address fits in 32 bits (all current designs)
    if {$hi2 eq "00"} {
        return "40'h${lo8hi}_${lo8lo}"
    } else {
        return "40'h${hi2}_${lo8hi}_${lo8lo}"
    }
}

# Generate the SystemVerilog include file.
set out_path [file join $script_dir cormorant_addr_map.svh]
set fp [open $out_path w]

puts $fp "// cormorant_addr_map.svh"
puts $fp "// AUTO-GENERATED by gen_addr_map.tcl — do not edit manually."
puts $fp "// Regenerate: source gen_addr_map.tcl  (Vivado Tcl console)"
puts $fp "// Source HWH: [file tail $hwh_path]"
puts $fp ""

# Emit one localparam per kernel, sorted for deterministic output.
foreach inst [lsort [array names bases]] {
    set sv [to_sv40 $bases($inst)]
    puts $fp "localparam logic \[39:0\] ${inst}_BASE = ${sv};"
}

close $fp
puts "gen_addr_map.tcl: wrote [file tail $out_path] ([array size bases] kernels)"
foreach inst [lsort [array names bases]] {
    puts "  ${inst}_BASE = [to_sv40 $bases($inst)]"
}
